apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: default
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'movies-api'
        static_configs:
          - targets: ['movies-api-service.default.svc.cluster.local:8000']
