apiVersion: v1
kind: Service
metadata:
  namespace: movies
  name: prometheus-service
spec:
  selector:
    app: prometheus
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 30092
  type: NodePort
