kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30091
        hostPort: 30091
      - containerPort: 30092
        hostPort: 30092
      - containerPort: 30093
        hostPort: 30093
  - role: worker
  - role: worker
  - role: worker
