apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-scripts
data:
  init.sql: |
    CREATE TABLE movies (
      id SERIAL PRIMARY KEY,
      titulo VARCHAR(100),
      ano INT,
      diretor VARCHAR(100)
    );

    INSERT INTO movies (titulo, ano, diretor) VALUES
      ('The Shawshank Redemption', 1994, 'Frank Darabont'),
      ('The Godfather', 1972, 'Francis Ford Coppola'),
      ('The Dark Knight', 2008, 'Christopher Nolan'),
      ('Pulp Fiction', 1994, 'Quentin Tarantino'),
      ('Forrest Gump', 1994, 'Robert Zemeckis'),
      ('Inception', 2010, 'Christopher Nolan'),
      ('Fight Club', 1999, 'David Fincher'),
      ('The Matrix', 1999, 'The Wachowskis'),
      ('The Godfather: Part II', 1974, 'Francis Ford Coppola'),
      ('The Empire Strikes Back', 1980, 'Irvin Kershner');
