apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: movies
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
  storageClassName: standard
