apiVersion: apps/v1
kind: Deployment
metadata:
  name: movies-api
spec:
  replicas: 4
  selector:
    matchLabels:
      app: movies-api
  template:
    metadata:
      labels:
        app: movies-api
    spec:
      containers:
        - name: movies-api
          image: moisesreis/movies-api:latest
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: "postgresql://admin:admin@postgres-service:5432/database"
          volumeMounts:
            - name: movies-api-volume
              mountPath: /app/movies-api
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
      volumes:
        - name: movies-api-volume
          persistentVolumeClaim:
            claimName: movies-api-pvc
