apiVersion: v1
kind: PersistentVolume
metadata:
  name: movies-api-pv
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/movies-api
  persistentVolumeReclaimPolicy: Delete
