apiVersion: v1
kind: Service
metadata:
  name: movies-api-service
spec:
  selector:
    app: movies-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30000
  type: NodePort
