apiVersion: apps/v1
kind: Deployment
metadata:
  name: jmeter
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jmeter
  template:
    metadata:
      labels:
        app: jmeter
    spec:
      containers:
        - name: jmeter
          image: justb4/jmeter:latest
          command: [ "jmeter", "-n", "-t", "/test-plan/test-plan.jmx", "-l", "/test-plan/result.jtl" ]
          volumeMounts:
            - name: jmeter-test-plan
              mountPath: /test-plan
      volumes:
        - name: jmeter-test-plan
          configMap:
            name: jmeter-test-plan
