apiVersion: v1
kind: Service
metadata:
  namespace: movies
  name: grafana-service
spec:
  selector:
    app: grafana
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30093
  type: NodePort
