name: teste_noturno
on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  teste_noturno:
    runs-on: self-hosted
    steps:
      - name: "Iniciando Job"
        run: echo "Iniciando Job"
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Setup Python"
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: "Instalando Dependências"
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: "Executando Testes"
        run: pytest --maxfail=1 --disable-warnings -q"
